# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['example_markdown_fr', 'parsed_markdown', 'split_lines', 'parse_bullet_line', 'add_bullet_to_container',
           'new_subsection_container', 'markdown_to_nested_dict', 'render_cv_html', 'html_to_pdf', 'fix_photo_path',
           'fix_asset_paths']

# %% ../nbs/00_core.ipynb #0481c053
example_markdown_fr='''# Informations personnelles
- Nom: Suvam Bhattacharya
- Titre: Data Scientist | Data Analytics | Scientific Computing
- Localisation: France
- Photo: ../static/photo.jpeg

# Résumé
Data scientist spécialisé en modélisation statistique et machine learning, avec une forte expertise en ingénierie des données. Expérience en Python, SQL, DevOps et environnements cloud. Conception de modèles prédictifs et de pipelines scalables et reproductibles, avec un accent sur l’automatisation, la robustesse et la fiabilité des résultats.

# Contact
- Email: fmahuyac@gmail.com
- Téléphone: +33663299291
- LinkedIn: https://www.linkedin.com/in/xxxxx/
- GitHub: https://github.com/xxxxx

# Compétences
## Langages
- Python
- SQL
- Bash
- MATLAB

## Cloud & DevOps
- AWS
- Terraform
- EKS
- CI/CD
- GitLab CI
- Slurm

## Data Engineering
- ETL (PostgreSQL, MySQL, Power BI, Tableau, Talend)
- Data Warehousing
- Modélisation des données
- Qualité des données

## Machine Learning
- Machine Learning
- ARIMA, SARIMA
- NLP, LLM
- Deeplearning




# Expérience
## Ingénieur Data / Cloud @ Eolen AS+
- Durée: 2024
- Localisation: Bruyères-le-Châtel
- Technologies: AWS, Terraform, EKS, Slurm, GitLab CI, Bash, Python
- Détail: Mise en place de pipelines CI/CD pour le déploiement d’environnements de simulation haute performance distribués.
- Détail: Conception de workflows reproductibles (migration, maintainance, troubleshooting) pour le traitement de données à grande échelle (Big Data).
- Détail: Optimisation de l’utilisation des ressources de calcul et de stockage sur infrastructure cloud.
- Détail: Contribution à la réponse à des appels d’offres.

## Data Scientist Freelance
- Durée: 2023
- Localisation:
- Technologies: Machine Learning, AWS, Python, SQL
- Détail: Développement de modèles de prévision de rupture de stock basés sur des séries temporelles (SARIMA/Prophet).
- Détail: Conception de pipelines de données et mise en place d’un data warehouse sur AWS/Talend.
- Détail: Analyse des résultats de ventes et contribution à la prise de décision stratégique PowerBI/Excel.

## Enseignant en Informatique @ I.U.T.
- Durée: 2019 - 2021
- Localisation: Orsay
- Technologies: POO, algorithmes avancés
- Détail: Enseignement de la programmation orientée objet et des structures algorithmiques.
- Détail: Encadrement de projets étudiants data et accompagnement pédagogique.

## Doctorant en Physique @ LPS
- Durée: 2018 - 2022
- Localisation: Orsay
- Technologies: Python, numpy, scikit-learn, matplotlib, pytorch
- Détail: Analyse statistique de données expérimentales complexes (prétraitement, filtrage, réduction de bruit).
- Détail: Modélisation de systèmes quantiques et ajustement de modèles à partir de données expérimentales.
- Détail: Application de méthodes de machine learning (régression, classification) pour l’extraction de motifs et l’interprétation des données.
- Détail: Développement d’outils d’analyse et de visualisation sous Jupyter Notebook pour l’exploration et la validation des résultats.
- Détail: Validation expérimentale et évaluation des modèles (robustesse, reproductibilité, interprétabilité).
- Détail: Thèse : https://theses.hal.science/tel-03577251/

## Stagiaire de recherche @ CNRS – Thales
- Durée: févr. 2018 - août 2018
- Localisation: Palaiseau
- Technologies: MATLAB, physique expérimentale
- Détail: Analyse de données expérimentales et traitement statistique de mesures physiques.
- Détail: Étude du gaz d’électrons bidimensionnel au sein du groupe de Albert Fert (Nobel `07).
- Détail: https://advanced.onlinelibrary.wiley.com/doi/abs/10.1002/adma.202102102

# Activités complémentaires
## Communauté IA & Mentorat
- Détail: Animation d’une communauté Discord dédiée à l’intelligence artificielle.
- Détail: Accompagnement d’étudiants en data science (debugging, compréhension des concepts).
- Détail: Transmission de bonnes pratiques en résolution de problèmes et structuration du raisonnement.

# Éducation
## Diplôme d’ingénieur (Le Cycle Ingénieur polytechnicien)
- Institution: École Polytechnique
- Localisation: Palaiseau
- Année: 2014 - 2018
- Spécialisation : Physique, mathematique, informatique

# Certifications

## Data Management
- Émetteur: Datascientest, Paris
- Année: 2023

## AWS Certified Solutions Architect – Associate
- Émetteur: AWS
- Année: 2024

## Applied Machine Learning in Python
- Émetteur: University of Michigan
- Année:

## Introduction to Data Science in Python
- Émetteur: University of Michigan
- Année:

## Machine Learning in Production
- Émetteur: DeepLearning.AI
- Année: '''

# %% ../nbs/00_core.ipynb #73ec91a8
import re
from pathlib import Path
from jinja2 import Environment, FileSystemLoader


# %% ../nbs/00_core.ipynb #6d56b8ab
def split_lines(markdown: str) -> list[str]:
    return markdown.replace("\r\n", "\n").replace("\r", "\n").split("\n")

# %% ../nbs/00_core.ipynb #e90c0593
def parse_bullet_line(line: str) -> tuple[str | None, str]:
    """
    Parse a bullet line.

    Returns:
    - ('Nom', 'CV Special19') for: - Nom: CV Special19
    - (None, 'Python') for: - Python
    """
    stripped = line.strip()

    m = re.match(r"^-\s*([^:]+)\s*:\s*(.*)$", stripped)
    if m:
        return m.group(1).strip(), m.group(2).strip()

    m = re.match(r"^-\s*(.+)$", stripped)
    if m:
        return None, m.group(1).strip()

    raise ValueError(f"Line is not a bullet line: {line}")

# %% ../nbs/00_core.ipynb #e7c4a304
def add_bullet_to_container(container: dict | list, key: str | None, value: str) -> dict | list:
    """
    Add a parsed bullet to either a dict or a list.

    Rules:
    - key:value bullets belong in dicts
    - plain bullets belong in lists
    - repeated dict keys become lists
    """
    if key is None:
        if isinstance(container, list):
            container.append(value)
            return container

        raise ValueError("Cannot add plain bullet item to dict container")

    if isinstance(container, dict):
        if key not in container:
            container[key] = value
        else:
            if not isinstance(container[key], list):
                container[key] = [container[key]]
            container[key].append(value)
        return container

    raise ValueError("Cannot add key:value bullet to list container")

# %% ../nbs/00_core.ipynb #63f2cefa
def new_subsection_container(first_bullet_key: str | None) -> dict | list:
    """
    Decide subsection container type from the first bullet encountered.
    """
    if first_bullet_key is None:
        return []
    return {}

# %% ../nbs/00_core.ipynb #32540bf3
def markdown_to_nested_dict(markdown: str) -> dict:
    """
    Convert CV markdown into a nested dictionary using only its structure.

    Rules:
    - # Section -> top-level key
    - ## Subsection -> nested key under current section
    - Plain text directly under # Section -> stored as string
    - - key: value -> dictionary entry
    - - item -> list entry
    - repeated - key: value -> list of values
    - repeated ## subsection titles -> become a list
    """
    result = {}

    current_h1 = None
    current_h2 = None

    h1_container = None
    h2_container = None
    h1_text_lines = []

    def flush_h1_text():
        nonlocal h1_text_lines, h1_container
        if current_h1 is None or h1_container is None:
            h1_text_lines = []
            return

        text = "\n".join(line.strip() for line in h1_text_lines if line.strip()).strip()
        if text:
            result[current_h1] = text
        h1_text_lines = []

    def flush_h2():
        nonlocal current_h2, h2_container, h1_container

        if current_h1 is None or current_h2 is None or h2_container is None:
            return

        if current_h2 not in h1_container:
            h1_container[current_h2] = h2_container
        else:
            if not isinstance(h1_container[current_h2], list):
                h1_container[current_h2] = [h1_container[current_h2]]
            h1_container[current_h2].append(h2_container)

        current_h2 = None
        h2_container = None

    def flush_h1():
        nonlocal current_h1, h1_container
        if current_h1 is None:
            return

        if h1_container is not None and current_h1 not in result:
            result[current_h1] = h1_container

        current_h1 = None
        h1_container = None

    for line in split_lines(markdown):
        stripped = line.strip()

        if not stripped:
            continue

        h1_match = re.match(r"^#\s+(.*)$", stripped)
        if h1_match:
            flush_h2()
            flush_h1_text()
            flush_h1()

            current_h1 = h1_match.group(1).strip()
            h1_container = {}
            current_h2 = None
            h2_container = None
            continue

        h2_match = re.match(r"^##\s+(.*)$", stripped)
        if h2_match:
            flush_h2()

            current_h2 = h2_match.group(1).strip()
            h2_container = None
            continue

        if stripped.startswith("- "):
            key, value = parse_bullet_line(stripped)

            if current_h2 is not None:
                if h2_container is None:
                    h2_container = new_subsection_container(key)
                h2_container = add_bullet_to_container(h2_container, key, value)
            else:
                if h1_container is None:
                    h1_container = {}
                if key is None:
                    raise ValueError(
                        f"Plain bullet item found directly under section '{current_h1}', "
                        "but no subsection exists to hold a list."
                    )
                h1_container = add_bullet_to_container(h1_container, key, value)

            continue

        if current_h2 is None:
            h1_text_lines.append(stripped)
        else:
            raise ValueError(
                f"Unexpected free text inside subsection '{current_h2}': {stripped}"
            )

    flush_h2()
    flush_h1_text()
    flush_h1()

    return result

# %% ../nbs/00_core.ipynb #81bf7b4b
parsed_markdown = markdown_to_nested_dict(example_markdown_fr)
parsed_markdown

# %% ../nbs/00_core.ipynb #d4517d21
def render_cv_html(data: dict, template_name: str = "cv_fr.html", theme_css: str = "cv_fr.css") -> str:
    #templates_dir = Path("templates/")
    templates_dir = Path("..") / "templates"
    env = Environment(
        loader=FileSystemLoader(templates_dir),
        autoescape=True,
    )

    template = env.get_template(template_name)
    html = template.render(data=data, theme_css=theme_css)
    return html

# %% ../nbs/00_core.ipynb #b7858eb9
from weasyprint import HTML, CSS

def html_to_pdf(html: str, output_path: str = "../output/cv.pdf"):
    HTML(string=html).write_pdf(
    "cv.pdf",
    stylesheets=[CSS("../templates/cv_fr.css")]
    )


# %% ../nbs/00_core.ipynb #704d42ae
print(parsed_markdown["Informations personnelles"]["Photo"])

from pathlib import Path

def fix_photo_path(data: dict) -> dict:
    photo = data.get("Informations personnelles", {}).get("Photo")

    if photo:
        abs_path = Path(photo).resolve()
        data["Informations personnelles"]["Photo"] = f"file://{abs_path}"

    return data
fix_photo_path(parsed_markdown)
print(parsed_markdown["Informations personnelles"]["Photo"])


# %% ../nbs/00_core.ipynb #04f77270
from pathlib import Path

def fix_asset_paths(data: dict) -> dict:
    lk = Path("../static/linkedin-svgrepo-com.svg").resolve()
    gt = Path("../static/logo-github-svgrepo-com.svg").resolve()
    data["assets"] = {
        "linkedin_icon": f"file://{lk}",
        "github_icon": f"file://{gt}",
    }
    print(data["assets"])
    return data


# %% ../nbs/00_core.ipynb #fe28f1fd
fix_asset_paths(parsed_markdown)
