# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_document.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/02_document.ipynb #38ff682dbf66d05f
import re
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

