# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_document.ipynb.

# %% auto #0
__all__ = ['Language', 'Contact', 'SkillCategory', 'Experience', 'Project', 'Education', 'Certification', 'CVDocument']

# %% ../nbs/03_document.ipynb #38ff682dbf66d05f
import re
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML, CSS

# %% ../nbs/03_document.ipynb #5cf3f027c83b8ef1
from dataclasses import dataclass, field
from typing import Literal

# %% ../nbs/03_document.ipynb #ab4b892cc5cc5b0c
Language = Literal["en", "fr"]

# %% ../nbs/03_document.ipynb #3bb778e167e4c298
@dataclass
class Contact:
    email: str = ""
    phone: str = ""
    linkedin: str = ""
    github: str = ""

    def as_dict(self) -> dict:
        return {
            "email": self.email,
            "phone": self.phone,
            "linkedin": self.linkedin,
            "github": self.github,
        }

# %% ../nbs/03_document.ipynb #ef156b57fa2da1fd
@dataclass
class SkillCategory:
    category: str = ""
    items: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "category": self.category,
            "items": self.items,
        }

# %% ../nbs/03_document.ipynb #926dff9b6707f0f6
@dataclass
class Experience:
    role: str = ""
    company: str = ""
    location: str = ""
    start_date: str = ""
    end_date: str = ""
    bullets: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "role": self.role,
            "company": self.company,
            "location": self.location,
            "start_date": self.start_date,
            "end_date": self.end_date,
            "bullets": self.bullets,
        }

# %% ../nbs/03_document.ipynb #f65b0ead15284b76
@dataclass
class Project:
    name: str = ""
    description: str = ""
    technologies: list[str] = field(default_factory=list)
    link: str = ""

    def as_dict(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "technologies": self.technologies,
            "link": self.link,
        }

# %% ../nbs/03_document.ipynb #3ebcd133ba892c17
@dataclass
class Education:
    degree: str = ""
    institution: str = ""
    location: str = ""
    start_date: str = ""
    end_date: str = ""
    details: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "degree": self.degree,
            "institution": self.institution,
            "location": self.location,
            "start_date": self.start_date,
            "end_date": self.end_date,
            "details": self.details,
        }

# %% ../nbs/03_document.ipynb #6c24ae52ab7452da
@dataclass
class Certification:
    name: str = ""
    issuer: str = ""
    date: str = ""
    link: str = ""

    def as_dict(self) -> dict:
        return {
            "name": self.name,
            "issuer": self.issuer,
            "date": self.date,
            "link": self.link,
        }

# %% ../nbs/03_document.ipynb #c05615113b3c2c35
from pathlib import Path

@dataclass
class CVDocument:
    language: Language = "en"

    name: str = ""
    title: str = ""
    location: str = ""
    summary: str = ""


    photo_path: str = f"file://{Path("static/photo.jpeg").resolve()}"
    linkedin_logo_path: str = f"file://{Path("static/linkedin-svgrepo-com.svg").resolve()}"
    github_logo_path: str = f"file://{Path("static/logo-github-svgrepo-com.svg").resolve()}"

    contact: Contact = field(default_factory=Contact)
    skills: list[SkillCategory] = field(default_factory=list)
    experience: list[Experience] = field(default_factory=list)
    projects: list[Project] = field(default_factory=list)

    education: list[Education] = field(default_factory=list)
    certifications: list[Certification] = field(default_factory=list)

    def is_french(self) -> bool:
        return self.language == "fr"

    def is_english(self) -> bool:
        return self.language == "en"

    def set_language(self, language: Language) -> None:
        self.language = language

    def set_photo(self, photo_path: str) -> None:
        self.photo_path = photo_path

    def assets(self) -> dict:
        return {
            "linkedin_logo": self.linkedin_logo_path,
            "github_logo": self.github_logo_path,
        }

    def as_dict(self) -> dict:
        return {
            "language": self.language,
            "name": self.name,
            "title": self.title,
            "location": self.location,
            "summary": self.summary,
            "contact": self.contact.as_dict(),
            "photo": self.photo_path,
            "assets": self.assets(),
            "skills": [skill.as_dict() for skill in self.skills],
            "experience": [exp.as_dict() for exp in self.experience],
            "projects": [proj.as_dict() for proj in self.projects],
            "education": [edu.as_dict() for edu in self.education],
            "certifications": [cert.as_dict() for cert in self.certifications],
        }
