# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_document.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/04_document.ipynb #c5822a505bce8f8
import re
from pathlib import Path
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML, CSS
from dataclasses import dataclass, field
from typing import Literal
