# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_mapper.ipynb.

# %% auto #0
__all__ = ['cv_template']

# %% ../nbs/02_mapper.ipynb #initial_id
from .document import CVDocument

def cv_template(cv: CVDocument) -> dict:
    d = cv.as_dict()

    return {
        "Informations personnelles": {
            "Nom": d["name"],
            "Titre": d["title"],
            "Localisation": d["location"],
            "Photo": d["photo"],
        },

        "Résumé": d["summary"],

        "Contact": {
            "Email": d["contact"]["email"],
            "Téléphone": d["contact"]["phone"],
            "LinkedIn": d["contact"]["linkedin"],
            "GitHub": d["contact"]["github"],
        },

        "Compétences": {
            skill["category"]: skill["items"]
            for skill in d["skills"]
        },

        "Expérience": {
            i: {
                "Role": exp["role"],
                "Company": exp["company"],
                "Localisation": exp["location"],
                "Durée": (
                    f"{exp['start_date']} - {exp['end_date']}"
                    if exp["start_date"] and exp["end_date"]
                    else exp["start_date"] or exp["end_date"]
                ),
                "Technologies": "",
                "Détail": exp["bullets"],
            }
            for i, exp in enumerate(d["experience"])
        },

        "Projets": {
            proj["name"]: {
                "Technologies": ", ".join(proj["technologies"]),
                "Détail": [
                    item for item in [proj["description"], proj["link"]]
                    if item
                ],
            }
            for proj in d["projects"]
        },

        # Important: template uses "Formation", not "Éducation"
        "Formation": {
            edu["degree"]: {
                "Institution": edu["institution"],
                "Localisation": edu["location"],
                "Année": (
                    f"{edu['start_date']} - {edu['end_date']}"
                    if edu["start_date"] and edu["end_date"]
                    else edu["start_date"] or edu["end_date"]
                ),
                "Détail": edu["details"],
            }
            for edu in d["education"]
        },

        "Certifications": {
            cert["name"]: {
                "Émetteur": cert["issuer"],
                "Année": cert["date"],
            }
            for cert in d["certifications"]
        },

        "assets": {
            "linkedin_icon": d["assets"]["linkedin_logo"],
            "github_icon": d["assets"]["github_logo"],
        },
    }
