# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_render.ipynb.

# %% auto #0
__all__ = ['render_cv_html', 'html_to_pdf', 'save_pdf']

# %% ../nbs/03_render.ipynb #71338c468ae109f6
from .document import CVDocument
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

# %% ../nbs/03_render.ipynb #initial_id
def render_cv_html(
    cv: CVDocument,
    template_name: str = "cv_fr.html",
    theme_css: str = "cv2_fr.css",
    templates_dir: str | Path = "../templates",
) -> str:
    templates_dir = Path(templates_dir)

    env = Environment(
        loader=FileSystemLoader(templates_dir),
        autoescape=True,
    )

    template = env.get_template(template_name)

    return template.render(
        data=cv_template(cv),
        theme_css=theme_css
    )

# %% ../nbs/03_render.ipynb #4f4a50a7a424c617
from weasyprint import HTML, CSS

def html_to_pdf(
    html: str,
    output_path: str | Path = "../output/data_scientist.pdf",
    css_path: str | Path = "../templates/cv_fr.css",
) -> Path:
    output_path = Path(output_path)
    css_path = Path(css_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    HTML(string=html).write_pdf(
        target=str(output_path),
        stylesheets=[CSS(filename=str(css_path))],
    )

    return Path(output_path)

# %% ../nbs/03_render.ipynb #cee36aad3ebdaa6
from .mapper import cv_template

def save_pdf(cv: CVDocument, company:str, role:str, output_path: str | Path = Path("../outputs/cv/")):

    html = render_cv_html(
        cv,
        template_name="cv_fr.html",
        theme_css="cv2_fr.css",
    )
    filename = f"{company}_{role}_cv_suvam_bhattacharya.pdf"
    output_path = Path(output_path) / filename

    pdf_path = html_to_pdf(
        html,
        output_path=output_path,
        css_path="../templates/cv2_fr.css",
    )

    return pdf_path
